<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 11,
                'user_id' => 2,
                'invoice' => 'INV/20260422/268',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 60000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 80000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => 'OKE',
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-04-22 17:31:18',
                'updated_at' => '2026-04-22 17:31:38',
            ),
            1 => 
            array (
                'id' => 12,
                'user_id' => 2,
                'invoice' => 'INV/20260422/775',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 50000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 70000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => 'asd',
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-04-22 17:32:34',
                'updated_at' => '2026-04-29 12:40:54',
            ),
            2 => 
            array (
                'id' => 13,
                'user_id' => 2,
                'invoice' => 'INV/20260422/883',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 60000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 80000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-04-22 17:43:19',
                'updated_at' => '2026-04-29 12:40:51',
            ),
            3 => 
            array (
                'id' => 14,
                'user_id' => 2,
                'invoice' => 'INV/20260422/743',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 50000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 70000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-04-22 17:47:45',
                'updated_at' => '2026-04-29 12:40:49',
            ),
            4 => 
            array (
                'id' => 15,
                'user_id' => 2,
                'invoice' => 'INV/20260503/321',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 110000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 130000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => 'tinggalkan di depan pagar saja',
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-05-03 13:15:33',
                'updated_at' => '2026-05-03 13:20:04',
            ),
            5 => 
            array (
                'id' => 16,
                'user_id' => 2,
                'invoice' => 'INV/20260514/354',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 105000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 125000,
                'status' => 'Selesai',
                'no_resi' => '1234567',
                'catatan' => NULL,
                'alasan_retur' => 'jelek',
                'status_retur' => 'Diajukan',
                'bukti_retur' => NULL,
                'created_at' => '2026-05-14 03:48:55',
                'updated_at' => '2026-05-14 04:00:14',
            ),
            6 => 
            array (
                'id' => 17,
                'user_id' => 2,
                'invoice' => 'INV/20260514/454',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 40000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 60000,
                'status' => 'Selesai',
                'no_resi' => '666',
                'catatan' => NULL,
                'alasan_retur' => 's',
                'status_retur' => 'Ditolak',
                'bukti_retur' => 'uploads/retur/1778754115_retur_785_retur_proof.jpg',
                'created_at' => '2026-05-14 16:40:13',
                'updated_at' => '2026-05-14 17:22:31',
            ),
            7 => 
            array (
                'id' => 18,
                'user_id' => 2,
                'invoice' => 'INV/20260515/499',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 55000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 75000,
                'status' => 'Menunggu Pembayaran',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-05-15 22:02:23',
                'updated_at' => '2026-05-15 22:02:23',
            ),
            8 => 
            array (
                'id' => 19,
                'user_id' => 2,
                'invoice' => 'INV/20260515/615',
                'alamat_pengiriman' => 'yuka No.A1',
                'total_harga' => 60000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 80000,
                'status' => 'Menunggu Pembayaran',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-05-15 22:06:31',
                'updated_at' => '2026-05-15 22:06:31',
            ),
            9 => 
            array (
                'id' => 20,
                'user_id' => 4,
                'invoice' => 'INV/20260516/344',
                'alamat_pengiriman' => ' No.',
                'total_harga' => 50000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 70000,
                'status' => 'Menunggu Pembayaran',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-05-16 02:16:17',
                'updated_at' => '2026-05-16 02:16:17',
            ),
            10 => 
            array (
                'id' => 21,
                'user_id' => 6,
                'invoice' => 'INV/20260602/481',
                'alamat_pengiriman' => ' No.',
                'total_harga' => 20000,
                'diskon' => 0,
                'ongkir' => 20000,
                'total_bayar' => 40000,
                'status' => 'Selesai',
                'no_resi' => '1234567',
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-06-02 17:51:56',
                'updated_at' => '2026-06-02 17:56:36',
            ),
            11 => 
            array (
                'id' => 22,
                'user_id' => 6,
                'invoice' => 'INV/20260622/407',
                'alamat_pengiriman' => ' No.',
                'total_harga' => 50000,
                'diskon' => 0,
                'ongkir' => 0,
                'total_bayar' => 50000,
                'status' => 'Selesai',
                'no_resi' => NULL,
                'catatan' => NULL,
                'alasan_retur' => NULL,
                'status_retur' => NULL,
                'bukti_retur' => NULL,
                'created_at' => '2026-06-22 22:46:35',
                'updated_at' => '2026-06-22 22:47:24',
            ),
            12 => 
            array (
                'id' => 23,
                'user_id' => 4,
                'invoice' => 'INV/20260623/0C34E3',
                'alamat_pengiriman' => ' No.',
                'total_harga' => 55000,
                'diskon' => 0,
                'ongkir' => 0,
                'total_bayar' => 55000,
                'status' => 'Selesai',
                'no_resi' => '1234',
                'catatan' => NULL,
                'alasan_retur' => 'iugig',
                'status_retur' => 'Ditolak',
                'bukti_retur' => NULL,
                'created_at' => '2026-06-23 02:28:48',
                'updated_at' => '2026-06-23 02:29:44',
            ),
        ));
        
        
    }
}