<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'ye666',
                'email' => 'ye@gmail.com',
                'no_hp' => '086775675',
                'foto' => 'profile_2_1776842934.png',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/RkQMn/uLH7mvY8RKuentusswcoRLbTEhiH2Kph3rO.hteo9zp86W',
                'role' => 'admin',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-04-22 14:27:41',
                'updated_at' => '2026-05-14 16:22:16',
                'nomor_hp' => NULL,
                'alamat' => 'yuka',
                'no_rumah' => 'A1',
                'kode_pos' => '666',
                'vip_paket' => 'REGULER',
                'saldo' => 0,
                'foto_profil' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'pasha',
                'email' => 'psha@gmail.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZKuD5qiaFBGNg.n0RpC8iOXMgshjdWWCPKk5QIQGnPkok70oUjco6',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-04-30 17:17:33',
                'updated_at' => '2026-04-30 17:17:33',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'REGULER',
                'saldo' => 0,
                'foto_profil' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'aryo pasha',
                'email' => 'fein@gmail.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mMYHFgTw6KblRzxVP22arOZ.marl0qntjFWRlXq/5T3c8RWfXvF/6',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => '2026-07-18',
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-05-14 04:08:08',
                'updated_at' => '2026-06-20 18:29:58',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'SILVER',
                'saldo' => 10000,
                'foto_profil' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'tes',
                'email' => 'yes@gmail.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$D4xfi/mQYd60KNxgOAuPH.yB2kkh7.btDFqjOfciE3wqxEBeUKoMK',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-05-28 01:21:47',
                'updated_at' => '2026-05-28 01:21:47',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'REGULER',
                'saldo' => 0,
                'foto_profil' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'irvan susano',
                'email' => 'irvan@gmail.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$p5WvYOYlPoEVvXQ2OMkyme1Ad7WCuQPsnjQUQlZn.5Ao/trmvpyAq',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => 'rzyWSMNiIHhJg9uxp58YVxK6izX7Ze3PBJqPe8QcfC8rb1ZcRt4GaHWSDOdX',
                'created_at' => '2026-06-02 17:49:42',
                'updated_at' => '2026-06-02 18:01:27',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'SILVER',
                'saldo' => 210000,
                'foto_profil' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Test User',
                'email' => 'testuser_mobile@example.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$BBSUhDwP4GaHsMdWy2mlm.V7QlX7qb1VqW7eBJ/GTR/JmMlEM7bpO',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-06-21 01:57:50',
                'updated_at' => '2026-06-21 01:57:50',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'REGULER',
                'saldo' => 0,
                'foto_profil' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Test Mobile',
                'email' => 'mobile@test.com',
                'no_hp' => NULL,
                'foto' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$anMx9oZWiLIU7.hzJlYEyOt33WQw.gGBJvS17MkYWoPyvQCqlY.GK',
                'role' => 'user',
                'phone' => NULL,
                'address' => NULL,
                'house_number' => NULL,
                'zip_code' => NULL,
                'balance' => '0.00',
                'vip_tier' => 'Reguler',
                'member_until' => NULL,
                'status' => 'Aktif',
                'remember_token' => NULL,
                'created_at' => '2026-06-21 01:58:32',
                'updated_at' => '2026-06-21 01:58:32',
                'nomor_hp' => NULL,
                'alamat' => NULL,
                'no_rumah' => NULL,
                'kode_pos' => NULL,
                'vip_paket' => 'REGULER',
                'saldo' => 0,
                'foto_profil' => NULL,
            ),
        ));
        
        
    }
}